version: '3.1'
services:
    yii:
        build:
            context: php
            dockerfile: yii.Dockerfile
        volumes:
            - ../:/var/www
        tty: true
    tars:
        build:
            context: php
            dockerfile: tars.Dockerfile
        volumes:
            - ../:/var/www
        ports:
            - "9504:9504"
            - "9505:9505"
        tty: true
    workerman:
        build:
            context: php
            dockerfile: workerman.Dockerfile
        volumes:
            - ../:/var/www
        ports:
            - "9506:9506"
            - "9507:9507"
        tty: true
    swoft:
        # container_name: swoft
        image: swoft/swoft
        volumes:
            - ../:/var/www
        links:
            - mysql
            - redis
        ports:
            - "8001:8001"
            - "9501:9501"
        working_dir: /var/www/swoole/swoft
        stdin_open: true
        command: php -a
        tty: true
    mongo:
        image: mongo:4.0.0-rc4-xenial
        ports:
            - "27017:27017"
    kafka: # https://github.com/wurstmeister/kafka-docker
        image: wurstmeister/kafka:2.11-2.0.0
    influxdb:
        image: influxdb:1.4.3-alpine
        ports:
            - "8086:8086"
        #     - "8083:8083" # admin
        #     - "2003:2003" # graphite
        environment:
            INFLUXDB_DB: log
            INFLUXDB_USER: log
            INFLUXDB_USER_PASSWORD: logpass
        #     INFLUXDB_GRAPHITE_ENABLED: 1
        #     INFLUXDB_ADMIN_ENABLED: 1
        # volumes:
        #     - ./data/influxdb:/var/lib/influxdb
    grafana:
        image: grafana/grafana:5.1.0-beta1
        ports:
            - "3000:3000"
        environment:
            GF_SERVER_ROOT_URL: http://grafana.server.name
            GF_SECURITY_ADMIN_PASSWORD: secret